### ISSUE TITLE
Documentação do Sistema V1.0

### ISSUE THREAD

**Issue by diegoportort** [gabrieltrajanof/arquiteturaweb#1]
Subindo a versão 1.0 da Documentação do Sistema - Página do Arquiteto, na versão inicial 1.0, contendo Introdução e Descrição Geral do Sistema que criaremos. Segue:

[Doc Sistema 1.0.pdf](https://github.com/gabrieltrajanof/arquiteturaweb/files/13328833/Doc.Sistema.1.0.pdf)

**Comment by diegoportort** [comment]
Segue complemento da documentação anterior - versão 1.1 - da Documentação do Sistema - Página do Arquiteto. Nesta versão foram incluídos os itens 3 e 4: Requisitos Funcionais e Não Funcionais.

[Doc Sistema 1.1.pdf](https://github.com/gabrieltrajanof/arquiteturaweb/files/13328890/Doc.Sistema.1.1.pdf)

**Comment by gabrieltrajanof** [comment]
Commit DOC
